"use client";

import { FormEvent, useMemo, useState } from "react";
import { Activity, AlertTriangle, CalendarDays, ChevronDown, CircleCheck, Image as ImageIcon, LayoutDashboard, Monitor, MoreHorizontal, Play, Plus, Search, Settings, Upload, Video, Wifi, X } from "lucide-react";

type Display={id:number;name:string;branch:string;area:string;status:"online"|"warning"|"offline";player:"Android"|"Web";playlist:string;sync:string;cache:number;code:string};
type Schedule={id:number;title:string;target:string;time:string;dates:string;color:string;state:"กำลังแสดง"|"รอแสดง"};
const seed:Display[]=[
 {id:1,name:"Lobby Main",branch:"Bangkok Riverside",area:"ล็อบบี้",status:"online",player:"Android",playlist:"Welcome Bangkok",sync:"12 วินาทีที่แล้ว",cache:100,code:"BKK-L01"},
 {id:2,name:"Elevator A",branch:"Bangkok Riverside",area:"โถงลิฟต์ ชั้น 1",status:"online",player:"Web",playlist:"Dining & Spa",sync:"38 วินาทีที่แล้ว",cache:100,code:"BKK-E01"},
 {id:3,name:"Breakfast Hall",branch:"Chiang Mai Old Town",area:"ห้องอาหาร",status:"warning",player:"Web",playlist:"Breakfast Morning",sync:"4 นาทีที่แล้ว",cache:72,code:"CNX-R01"},
 {id:4,name:"Pool Entrance",branch:"Phuket Beach",area:"ทางเข้าสระว่ายน้ำ",status:"offline",player:"Android",playlist:"Pool & Activities",sync:"1 ชม. 24 นาที",cache:100,code:"HKT-P01"},
];
const scheduleSeed:Schedule[]=[
 {id:1,title:"Breakfast Morning",target:"Breakfast Hall",time:"06:00–10:30",dates:"ทุกวัน",color:"#f59e0b",state:"กำลังแสดง"},
 {id:2,title:"Welcome Bangkok",target:"Lobby Main",time:"ตลอดวัน",dates:"1–30 ก.ย.",color:"#14b8a6",state:"กำลังแสดง"},
 {id:3,title:"Weekend Spa Offer",target:"Bangkok Riverside",time:"10:00–22:00",dates:"ศ.–อา.",color:"#8b5cf6",state:"รอแสดง"},
];
function Status({status}:{status:Display["status"]}){const m={online:["ออนไลน์","ok"],warning:["ต้องตรวจสอบ","warn"],offline:["ออฟไลน์","bad"]} as const;return <span className={`status ${m[status][1]}`}><i/>{m[status][0]}</span>}

export default function Home(){
 const [tab,setTab]=useState("overview"),[query,setQuery]=useState(""),[branch,setBranch]=useState("ทุกสาขา"),[selected,setSelected]=useState<Display|null>(null),[toast,setToast]=useState(""),[displays,setDisplays]=useState(seed),[schedules,setSchedules]=useState(scheduleSeed),[registerOpen,setRegisterOpen]=useState(false),[scheduleOpen,setScheduleOpen]=useState(false);
 const filtered=useMemo(()=>displays.filter(d=>(branch==="ทุกสาขา"||d.branch===branch)&&`${d.name} ${d.branch} ${d.area}`.toLowerCase().includes(query.toLowerCase())),[displays,query,branch]);
 const notify=(s:string)=>{setToast(s);window.setTimeout(()=>setToast(""),2400)};
 const repair=(d:Display)=>{const fixed={...d,cache:100,status:"online" as const,sync:"เมื่อสักครู่"};setDisplays(v=>v.map(x=>x.id===d.id?fixed:x));setSelected(fixed);notify(`เริ่มซ่อมแซม Cache ของ ${d.name} แล้ว`)};
 const register=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);const item:Display={id:Date.now(),name:String(f.get("name")),branch:String(f.get("branch")),area:String(f.get("area")),player:String(f.get("player")) as Display["player"],status:"online",playlist:"ยังไม่ได้กำหนด",sync:"เมื่อสักครู่",cache:0,code:String(f.get("pairCode")).toUpperCase()};setDisplays(v=>[item,...v]);setRegisterOpen(false);notify(`ลงทะเบียน ${item.name} สำเร็จ`)};
 const createSchedule=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);const item:Schedule={id:Date.now(),title:String(f.get("playlist")),target:String(f.get("target")),dates:String(f.get("start"))+" – "+String(f.get("end")),time:String(f.get("startTime"))+"–"+String(f.get("endTime")),state:"รอแสดง",color:"#0f9f91"};setSchedules(v=>[item,...v]);setScheduleOpen(false);notify(`ตั้งงาน ${item.title} ให้ ${item.target} แล้ว`)};

 const displayTable=<div className="display-table"><div className="table-row table-label"><span>DISPLAY</span><span>กำลังแสดง</span><span>OFFLINE CACHE</span><span>สถานะ</span><span/></div>{filtered.map(d=><button key={d.id} className="table-row display-row" onClick={()=>setSelected(d)}><span className="display-name"><i className={d.status}><Monitor/></i><span><strong>{d.name}</strong><small>{d.branch} · {d.area}</small></span></span><span><strong>{d.playlist}</strong><small>{d.player} Player · {d.code}</small></span><span className="cache"><strong>{d.cache}%</strong><i><b style={{width:`${d.cache}%`}} className={d.cache<100?"warnbar":""}/></i></span><span><Status status={d.status}/><small>{d.sync}</small></span><MoreHorizontal/></button>)}</div>;

 return <main className="app-shell">
  <aside className="sidebar"><div className="brand"><span className="brand-mark">S</span><div><strong>StayScreen</strong><small>Hotel Signage</small></div></div><nav><p>จัดการระบบ</p><button className={tab==="overview"?"active":""} onClick={()=>setTab("overview")}><LayoutDashboard/>ภาพรวม</button><button className={tab==="displays"?"active":""} onClick={()=>setTab("displays")}><Monitor/>Manage Displays <b>{displays.length}</b></button><button onClick={()=>notify("กำลังเปิดคลังสื่อ")}><ImageIcon/>คลังสื่อ</button><button onClick={()=>notify("กำลังเปิดตัวจัดการ Playlist")}><Play/>Playlists</button><button className={tab==="schedules"?"active":""} onClick={()=>setTab("schedules")}><CalendarDays/>Schedules</button><p>ระบบ</p><button onClick={()=>notify("กำลังเปิดรายงาน Proof-of-play")}><Activity/>รายงานการเล่น</button><button onClick={()=>notify("กำลังเปิดการตั้งค่าองค์กร")}><Settings/>ตั้งค่า</button></nav><div className="account"><span>PS</span><div><strong>Pimchanok S.</strong><small>Platform Admin</small></div><ChevronDown/></div></aside>
  <section className="workspace"><header className="topbar"><div className="mobile-brand"><span className="brand-mark">S</span><strong>StayScreen</strong></div><label className="search"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="ค้นหา Display, Playlist หรือสาขา"/></label><div className="top-actions"><button className="icon-button"><AlertTriangle/></button><button className="primary" onClick={()=>notify("พร้อมรับไฟล์ภาพและวิดีโอ")}><Upload/>อัปโหลดสื่อ</button></div></header>
   <div className="content">
    <div className="page-title"><div><span className="eyebrow">BANGKOK RIVERSIDE GROUP</span><h1>{tab==="schedules"?"Schedules":tab==="displays"?"Manage Displays":"สวัสดี, พิมพ์ชนก"}</h1><p>{tab==="displays"?"ลงทะเบียน จัดกลุ่ม และตรวจสถานะจอทั้งหมด":tab==="schedules"?"กำหนดว่า Playlist ใด จะแสดงที่จอไหน และเวลาใด":"ภาพรวมการแสดงผลทุกสาขา"}</p></div><button className={tab==="displays"?"primary":"outline"} onClick={()=>tab==="displays"?setRegisterOpen(true):setScheduleOpen(true)}><Plus/>{tab==="displays"?"ลงทะเบียน Display":"สร้าง Schedule"}</button></div>

    {tab==="overview"&&<><div className="metrics"><article><span className="metric-icon teal"><Monitor/></span><div><small>Displays ทั้งหมด</small><strong>{displays.length}</strong><em>3 กำลังเชื่อมต่อ</em></div></article><article><span className="metric-icon green"><Wifi/></span><div><small>ออนไลน์</small><strong>{displays.filter(d=>d.status==="online").length}</strong><em>พร้อมรับงาน</em></div></article><article><span className="metric-icon amber"><AlertTriangle/></span><div><small>ต้องตรวจสอบ</small><strong>1</strong><em>Cache ไม่สมบูรณ์</em></div></article><article><span className="metric-icon violet"><Video/></span><div><small>งานที่กำลังแสดง</small><strong>2</strong><em>อีก 1 งานรอแสดง</em></div></article></div><div className="main-grid"><section className="panel displays-panel"><div className="panel-head"><div><h2>สถานะ Displays</h2><p>ติดตาม Player และไฟล์ Offline แบบเรียลไทม์</p></div><select value={branch} onChange={e=>setBranch(e.target.value)}><option>ทุกสาขา</option><option>Bangkok Riverside</option><option>Chiang Mai Old Town</option><option>Phuket Beach</option></select></div>{displayTable}</section><aside className="right-column"><section className="panel live-preview"><div className="panel-head"><div><h2>ภาพล่าสุดจากจอจริง</h2><p>Lobby Main · เมื่อ 12 วินาทีที่แล้ว</p></div><button onClick={()=>notify("ส่งคำขอ Screenshot ใหม่แล้ว")} className="link-button">ขอภาพใหม่</button></div><div className="screen-preview"><div className="hotel-copy"><small>RIVERSIDE ESCAPE</small><strong>Your stay,<br/>beautifully remembered.</strong><span>Welcome to Bangkok</span></div><span className="screen-badge"><i/> LIVE</span></div><div className="preview-meta"><span><small>PLAYLIST</small><strong>Welcome Bangkok</strong></span><span><small>MEDIA</small><strong>hero-riverside.mp4</strong></span><span><small>VERSION</small><strong>v18</strong></span></div></section><section className="alert-card"><AlertTriangle/><div><strong>Offline Cache ไม่สมบูรณ์</strong><p>Breakfast Hall มีไฟล์พร้อมใช้งาน 72% ระบบกำลังดาวน์โหลดซ่อมแซม</p><button onClick={()=>setSelected(displays.find(d=>d.name==="Breakfast Hall")||null)}>ดูรายละเอียด</button></div></section></aside></div></>}

    {tab==="displays"&&<><div className="setup-banner"><div className="pair-visual"><Monitor/><span>6</span></div><div><span className="eyebrow">QUICK SETUP</span><h2>เพิ่มจอใหม่ได้ใน 3 ขั้นตอน</h2><p>เปิด Web Player หรือ Android Player → ดูรหัส 6 หลักบนจอ → กรอกรหัสเพื่อลงทะเบียนและกำหนดสาขา</p></div><button className="primary" onClick={()=>setRegisterOpen(true)}><Plus/>ลงทะเบียนจอใหม่</button></div><section className="panel"><div className="panel-head"><div><h2>Displays ทั้งหมด</h2><p>{displays.length} จอใน 3 สาขา · เลือกจอเพื่อดูรายละเอียด</p></div><select value={branch} onChange={e=>setBranch(e.target.value)}><option>ทุกสาขา</option><option>Bangkok Riverside</option><option>Chiang Mai Old Town</option><option>Phuket Beach</option></select></div>{displayTable}</section></>}

    {tab==="schedules"&&<><div className="schedule-toolbar"><div className="scope-card"><CalendarDays/><div><small>ตารางงานที่เผยแพร่</small><strong>{schedules.length} Schedules</strong></div></div><div className="scope-card"><Monitor/><div><small>จอที่ได้รับงาน</small><strong>{new Set(schedules.map(s=>s.target)).size} เป้าหมาย</strong></div></div><button className="primary" onClick={()=>setScheduleOpen(true)}><Plus/>กำหนดงานให้จอ</button></div><section className="panel schedule-page"><div className="panel-head"><div><h2>ตารางเผยแพร่</h2><p>งานล่าสุดเรียงตามเวลาที่สร้าง</p></div><button className="link-button" onClick={()=>setScheduleOpen(true)}>สร้าง Schedule</button></div><div className="schedule-list full-list">{schedules.map(s=><article key={s.id}><i style={{background:s.color}}/><div><strong>{s.title}</strong><small>แสดงที่ {s.target}</small></div><span><small>ช่วงเวลา</small><strong>{s.time}</strong></span><span><small>ช่วงวันที่</small><strong>{s.dates}</strong></span><b className={s.state==="กำลังแสดง"?"running":"queued"}>{s.state}</b></article>)}</div></section></>}

    {tab==="overview"&&<section className="panel schedule-panel"><div className="panel-head"><div><h2>Schedules วันนี้</h2><p>งานที่กำลังแสดงและเตรียมเผยแพร่ล่วงหน้า</p></div><button className="link-button" onClick={()=>setTab("schedules")}>ดูทั้งหมด</button></div><div className="schedule-list">{schedules.slice(0,3).map(s=><article key={s.id}><i style={{background:s.color}}/><div><strong>{s.title}</strong><small>{s.target}</small></div><span><small>ช่วงเวลา</small><strong>{s.time}</strong></span><span><small>วันที่แสดง</small><strong>{s.dates}</strong></span><b className={s.state==="กำลังแสดง"?"running":"queued"}>{s.state}</b></article>)}</div></section>}
   </div>
  </section>

  {registerOpen&&<div className="modal-backdrop" onClick={()=>setRegisterOpen(false)}><form className="modal" onSubmit={register} onClick={e=>e.stopPropagation()}><button type="button" className="drawer-close" onClick={()=>setRegisterOpen(false)}><X/></button><span className="eyebrow">REGISTER DISPLAY</span><h2>ลงทะเบียนจอใหม่</h2><p>กรอกรหัส 6 หลักที่แสดงบน Player แล้วระบุตำแหน่งติดตั้ง</p><label>รหัสจับคู่ 6 หลัก<input name="pairCode" required minLength={6} maxLength={6} placeholder="เช่น 482913" pattern="[A-Za-z0-9]{6}"/></label><div className="form-grid"><label>ชื่อ Display<input name="name" required placeholder="เช่น Lobby Main"/></label><label>ประเภท Player<select name="player"><option>Android</option><option>Web</option></select></label></div><label>สาขา<select name="branch"><option>Bangkok Riverside</option><option>Chiang Mai Old Town</option><option>Phuket Beach</option></select></label><label>พื้นที่ติดตั้ง<input name="area" required placeholder="เช่น ล็อบบี้ ชั้น 1"/></label><div className="modal-actions"><button type="button" className="outline" onClick={()=>setRegisterOpen(false)}>ยกเลิก</button><button className="primary"><CircleCheck/>ยืนยันลงทะเบียน</button></div></form></div>}

  {scheduleOpen&&<div className="modal-backdrop" onClick={()=>setScheduleOpen(false)}><form className="modal wide" onSubmit={createSchedule} onClick={e=>e.stopPropagation()}><button type="button" className="drawer-close" onClick={()=>setScheduleOpen(false)}><X/></button><span className="eyebrow">NEW SCHEDULE</span><h2>กำหนดงานให้ Display</h2><p>เลือก Playlist และจอเป้าหมาย พร้อมกำหนดช่วงเวลาเผยแพร่</p><label>Playlist<select name="playlist"><option>Welcome Bangkok</option><option>Dining & Spa</option><option>Breakfast Morning</option><option>Pool & Activities</option></select></label><label>Display เป้าหมาย<select name="target">{displays.map(d=><option key={d.id}>{d.name}</option>)}</select></label><div className="form-grid"><label>วันที่เริ่ม<input name="start" type="date" required defaultValue="2026-09-13"/></label><label>วันที่สิ้นสุด<input name="end" type="date" required defaultValue="2026-09-30"/></label><label>เวลาเริ่ม<input name="startTime" type="time" required defaultValue="08:00"/></label><label>เวลาสิ้นสุด<input name="endTime" type="time" required defaultValue="22:00"/></label></div><div className="target-summary"><Monitor/><div><strong>งานนี้จะถูกส่งไปยังจอที่เลือก</strong><small>Player จะดาวน์โหลดสื่อล่วงหน้าและตรวจ Offline Cache ก่อนเวลาเริ่ม</small></div></div><div className="modal-actions"><button type="button" className="outline" onClick={()=>setScheduleOpen(false)}>บันทึก Draft</button><button className="primary"><CircleCheck/>Publish Schedule</button></div></form></div>}

  {selected&&<div className="drawer-backdrop" onClick={()=>setSelected(null)}><aside className="drawer" onClick={e=>e.stopPropagation()}><button className="drawer-close" onClick={()=>setSelected(null)}><X/></button><span className="eyebrow">DISPLAY DETAILS</span><h2>{selected.name}</h2><p>{selected.branch} · {selected.area}</p><div className="device-hero"><Monitor/><Status status={selected.status}/></div><dl><div><dt>Player</dt><dd>{selected.player}</dd></div><div><dt>รหัสเครื่อง</dt><dd>{selected.code}</dd></div><div><dt>Playlist</dt><dd>{selected.playlist}</dd></div><div><dt>Sync ล่าสุด</dt><dd>{selected.sync}</dd></div><div><dt>Offline cache</dt><dd>{selected.cache}% พร้อมใช้งาน</dd></div></dl><button className="primary full" onClick={()=>{setSelected(null);setScheduleOpen(true)}}><CalendarDays/>กำหนด Schedule ให้จอนี้</button>{selected.cache<100&&<button className="outline full" onClick={()=>repair(selected)}>ดาวน์โหลดซ่อมแซม Cache</button>}<button className="outline full" onClick={()=>notify("ส่งคำขอ Screenshot ใหม่แล้ว")}>ขอ Screenshot ใหม่</button></aside></div>}
  {toast&&<div className="toast">{toast}</div>}
 </main>
}
